[project]
name = "swarm"
version = "0.1.0"
description = "Development environment for RoboStack ROS packages"
authors = ["Your Name <your.email@example.com>"]
channels = ["https://fast.prefix.dev/conda-forge", "https://prefix.dev/robostack-noetic"]
platforms = ["linux-64"]  # , "win-64", "osx-64", "osx-arm64", "linux-aarch64"]

[dependencies]
python = "3.11.*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
ros-noetic-desktop = "*"
catkin_tools = "*"
rosdep = "*"
pcl = ">=1.14.1,<2"
uv = ">=0.7.13,<0.8"
fire = ">=0.7.0,<0.8"

[target.linux.dependencies]
libgl-devel = "*"

[pypi-dependencies]
ruff = ">=0.13.0,<0.14"
crazyflow = ">=0.0.2"

[environments]
docs = { features = ["docs"] }

[feature.docs.dependencies]
mkdocs = ">=1.5.3"
mkdocs-material = ">=9.4.0"
mkdocstrings = ">=0.24.0"
mkdocstrings-python = ">=1.7.0"
mkdocs-gen-files = ">=0.5.0"
mkdocs-literate-nav = ">=0.6.0"

[feature.docs.tasks]
docs-serve = { cmd = "mkdocs serve", description = "Serve docs locally" }
docs-build = { cmd = "mkdocs build", description = "Build docs" }
